### PR TITLE
Fix how setup runs ipfs init

### LINKED ISSUE #499: CLI setup fails on first run
# Summary

## Problem

The first run of `fission setup` fails to complete. 

### Impact

The user is not able to setup their account with a username and email. If they run the command a second time, they are able to do so.

## Solution

It seems that the initialization of the repo is not completed in time. One possible solution is to check `repo.lock` before moving on to the next command.

# Detail

**Describe the bug**

The setup command fails with `"Error: no IPFS repo found in /home/username/.config/fission/ipfs.\nplease run: 'ipfs init'"` error or a `Error: lock /home/username/.config/fission/ipfs/repo.lock: someone else has the lock`. 

**To Reproduce**
1. Delete `~/.config/fission`
2. Run `fission setup -v`

**Expected behavior**

The setup command should finish initialization and request a username and email to complete the setup process.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 and Ubuntu 20.04
 - Version: 2.10.2

**Additional context**

Full verbose output run on Ubuntu 20.04:

```
$ fission setup -v
2021-04-19 09:06:30.290315: [debug] 👀📖 Reading global config.yaml
2021-04-19 09:06:30.290751: [debug] 👀📖 Reading YAML from "/home/thuselem/.config/fission/config.yaml"
2021-04-19 09:06:30.290862: [debug] 🛑 Path does not exist
2021-04-19 09:06:30.290945: [warn] 🙋 Cannot find file
2021-04-19 09:06:30.291470: [debug] No cached server DID. Fetching from _did.runfission.com
2021-04-19 09:06:30.344946: [debug] DID retrieved did:key:zStEZpzSMtTt9k2vszgvCwF4fLQQSyA15W5AQ4z3AR6Bx4eFJ5crJFbuGxKmbma4
2021-04-19 09:06:30.345655: [debug] Setup (Options {forceOS = Nothing, maybeUsername = Nothing, maybeEmail = Nothing})
2021-04-19 09:06:30.345725: [debug] 👀📖 Reading global config.yaml
2021-04-19 09:06:30.345771: [debug] 👀📖 Reading YAML from "/home/thuselem/.config/fission/config.yaml"
2021-04-19 09:06:30.345826: [debug] 🛑 Path does not exist
2021-04-19 09:06:30.345865: [warn] 🙋 Cannot find file
2021-04-19 09:06:30.345906: [debug] Unable to parse config
2021-04-19 09:06:30.345946: [user] 🌱 Setting up environment
2021-04-19 09:06:30.345994: [user] 🪐 Downloading managed IPFS for Linux
2021-04-19 09:06:30.346051: [debug] 🌌📞 Making remote IPFS request to HTTP gateway https://ipfs.io
2021-04-19 09:07:00.819668: [debug] 🌌👍 Remote IPFS success
2021-04-19 09:07:00.820142: [debug] Writing IPFS binary to /home/thuselem/.config/fission/bin/fission-ipfs
2021-04-19 09:07:00.820524: [debug] ✍️  Writing to /home/thuselem/.config/fission/bin/fission-ipfs
2021-04-19 09:07:00.998358: [user] 🎛️  Configuring managed IPFS
2021-04-19 09:07:00.999388: [debug] 🌌🎬 Running local IPFS
2021-04-19 09:07:00.999530: [debug] ✍️  Writing to /home/thuselem/.config/fission/tmp/1416542b8addc7315f9e14896477c1d8ce5eead4765d303b7c53bdf6b7325546
2021-04-19 09:07:01.000876: [debug] 🌌⚙️  Running: IPFS_PATH=/home/thuselem/.config/fission/ipfs /home/thuselem/.config/fission/bin/fission-ipfs config --bool Swarm.EnableRelayHop true --timeout=3600s with arg Nothing
2021-04-19 09:07:01.108746: [warn] 🙋 "Error: no IPFS repo found in /home/thuselem/.config/fission/ipfs.\nplease run: 'ipfs init'\n"
2021-04-19 09:07:01.108941: [debug] 🌌🎬 Running local IPFS
2021-04-19 09:07:01.109041: [debug] ✍️  Writing to /home/thuselem/.config/fission/tmp/1416542b8addc7315f9e14896477c1d8ce5eead4765d303b7c53bdf6b7325546
2021-04-19 09:07:01.111486: [debug] 🌌⚙️  Running: IPFS_PATH=/home/thuselem/.config/fission/ipfs /home/thuselem/.config/fission/bin/fission-ipfs config Addresses.API /ip4/0.0.0.0/tcp/10235 --timeout=3600s with arg Nothing
generating ED25519 keypair...done
peer identity: 12D3KooWECedWNXf6WXZBfRdRc59LTdVSBn6LsF7oXM5BtWAzw1j
initializing IPFS node at /home/thuselem/.config/fission/ipfs
2021-04-19 09:07:01.297393: [warn] 🙋 "Error: lock /home/thuselem/.config/fission/ipfs/repo.lock: someone else has the lock\n"
2021-04-19 09:07:01.298026: [debug] 🌌🎬 Running local IPFS
2021-04-19 09:07:01.298135: [debug] ✍️  Writing to /home/thuselem/.config/fission/tmp/1416542b8addc7315f9e14896477c1d8ce5eead4765d303b7c53bdf6b7325546
2021-04-19 09:07:01.300606: [debug] 🌌⚙️  Running: IPFS_PATH=/home/thuselem/.config/fission/ipfs /home/thuselem/.config/fission/bin/fission-ipfs bootstrap add /dns4/node.runfission.com/tcp/4001/ipfs/QmVLEz2SxoNiFnuyLpbXsH6SvjPTrHNMU88vCQZyhgBzgw --timeout=3600s with arg Nothing
2021-04-19 09:07:01.470893: [debug] 🌌🎬 Running local IPFS
2021-04-19 09:07:01.471237: [debug] ✍️  Writing to /home/thuselem/.config/fission/tmp/1416542b8addc7315f9e14896477c1d8ce5eead4765d303b7c53bdf6b7325546
2021-04-19 09:07:01.473346: [debug] 🌌⚙️  Running: IPFS_PATH=/home/thuselem/.config/fission/ipfs /home/thuselem/.config/fission/bin/fission-ipfs bootstrap add /ip4/3.226.224.78/tcp/4001/p2p/QmPeeeZZXxMBAPxxba7a6ggjDr5jLuD3RAFnmPPcvJ9fMS --timeout=3600s with arg Nothing
to get started, enter:

	ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme

2021-04-19 09:07:01.701481: [debug] 🌌🎬 Running local IPFS
2021-04-19 09:07:01.701740: [debug] ✍️  Writing to /home/thuselem/.config/fission/tmp/1416542b8addc7315f9e14896477c1d8ce5eead4765d303b7c53bdf6b7325546
2021-04-19 09:07:01.703736: [debug] 🌌⚙️  Running: IPFS_PATH=/home/thuselem/.config/fission/ipfs /home/thuselem/.config/fission/bin/fission-ipfs bootstrap add /ip4/3.226.224.78/udp/4001/quic/p2p/QmPeeeZZXxMBAPxxba7a6ggjDr5jLuD3RAFnmPPcvJ9fMS --timeout=3600s with arg Nothing
2021-04-19 09:07:01.959102: [debug] 🌌 IPFS process completed successfully
2021-04-19 09:07:01.959298: [debug] 🌌🎬 Running local IPFS
2021-04-19 09:07:01.959410: [debug] ✍️  Writing to /home/thuselem/.config/fission/tmp/1416542b8addc7315f9e14896477c1d8ce5eead4765d303b7c53bdf6b7325546
2021-04-19 09:07:01.961781: [debug] 🌌⚙️  Running: IPFS_PATH=/home/thuselem/.config/fission/ipfs /home/thuselem/.config/fission/bin/fission-ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/11235 --timeout=3600s with arg Nothing
2021-04-19 09:07:02.208478: [debug] 🌌 IPFS process completed successfully
2021-04-19 09:07:02.208674: [warn] 🙋 "Error: no IPFS repo found in /home/thuselem/.config/fission/ipfs.\nplease run: 'ipfs init'\n"
```

### PR DESCRIPTION
**Pull request by walkah**
# Summary

This PR changes how we run `ipfs init` during setup. We already have a nice `IPFS.runLocal` wrapper that cleanly handles stdout / stderr and checks exit codes for the IPFS process. We use it everywhere *except* when calling `ipfs init`. On some platforms (sometimes?) ipfs init would not complete before the subsequent commands tried to run - resulting in error messages (ipfs repo locked). 

Fixes #499

### CODE REVIEW

File: fission-cli/library/Fission/CLI/IPFS/Configure.hs [hunk 1]
```diff
@@ -7,30 +7,24 @@ module Fission.CLI.IPFS.Configure
...
+init ::
+  ( MonadLocalIPFS m
+  , MonadRaise     m
+  , m `Raises` IPFS.Error
+  )
+  => m IPFS.RawMessage
 init = do
-  IPFS.BinPath ipfsPath <- globalIPFSBin
-  ipfsRepo              <- globalIPFSRepo
-   -- Needs to be run manually because it's a prerequesite for the daemon
```
Comment (walkah) [inline fission-cli/library/Fission/CLI/IPFS/Configure.hs:27]: this appeared to be not / no longer true.

Comment (expede) [reply fission-cli/library/Fission/CLI/IPFS/Configure.hs:27]: Gooood point!

**Review by expede — APPROVED** [review]
Lookin' good 😎
